Controllers/MovimentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAO;

namespace ControleFinanceiroWeb.Controllers
{
    public class MovimentoController : PageBase
    {
        private void CarregarComboEmpresas()
        {
            EmpresaDAO objDao = new EmpresaDAO();
            ViewBag.lstEmpresa = objDao.ConsultarEmpresa(CodigoLogado);
        }
        private void CarregarComboCategoria()
        {
            CategoriaDAO objDao = new CategoriaDAO();
            ViewBag.lstCategoria = objDao.ConsultarCategoria(CodigoLogado);
        }
        private void CarregarComboConta()
        {
            ContaDAO objDao = new ContaDAO();
            ViewBag.lstConta = objDao.ConsultarConta(CodigoLogado);
        }


        public ActionResult Filtrar(string tipo, string dataIni, string dataFim)
        {
            ViewBag.dtIni = dataIni;
            ViewBag.dtFim = dataFim;
            if (dataIni == "" || dataFim == "")
            {
                ViewBag.Ret = 0;
                ViewBag.Msg = Mensagens.Msg.MensagemCampoObg;
            }
            else
            {
                DateTime dtInicia = Convert.ToDateTime(dataIni);
                DateTime dtFinal = Convert.ToDateTime(dataFim);
                string tipoPes = tipo;
                FiltrarMov(tipoPes, dtInicia, dtFinal);
            }
            MontarTitulo(3);
            return View("Consultar");
        }
        private void FiltrarMov(string tipo, DateTime dtini, DateTime dtfim)
        {
            MovimentoDAO objDao = new MovimentoDAO();
            ViewBag.Mov = objDao.ConsultarMovimento(CodigoLogado, dtini, dtfim, tipo);
          
        }
        private void MontarTitulo(int tipoPag)
        {
            switch (tipoPag)
            {
                case 1:
                    ViewBag.Titulo = "Cadastro de Movimento";
                    ViewBag.SubTitulo = "Cadastre aqui seus Movimentos";
                    break;
                case 2:
                    ViewBag.Titulo = "Alterar Movimento";
                    ViewBag.SubTitulo = "Altere aqui seus Movimentos";
                    break;
                case 3:
                    ViewBag.Titulo = "Consulta de Movimento";
                    ViewBag.SubTitulo = "Consulte aqui seus Movimentos";
                    break;
            }
        }
      
        public ActionResult Lancar()
        {
            if (CodigoLogado == 0)
            {
                return RedirectToAction("Login", "Usuario");
            }

            CarregarComboCategoria();
            CarregarComboConta();
            CarregarComboEmpresas();
            MontarTitulo(1);
            return View();
        }
        public ActionResult Gravar(string data, string tipo, string valor, string categoria, string empresa,
            string conta, string obs)
        {
            if (CodigoLogado == 0)
            {
                return RedirectToAction("Login", "Usuario");
            }

            if (data == "" || tipo == "" || valor == "" || categoria == "" || empresa == "" || conta == "")
            {
                ViewBag.Ret = 0;
                ViewBag.Msg = Mensagens.Msg.MensagemCampoObg;
            }else
            {
                tb_movimento objmov = new tb_movimento();
                MovimentoDAO objDao = new MovimentoDAO();
                objmov.id_usuario = CodigoLogado;
                objmov.tipo_movimento = tipo;
                objmov.valor_movimento = Convert.ToDecimal(valor);
                objmov.data_movimento = Convert.ToDateTime(data);
                objmov.obs_movimento = obs;
                objmov.id_empresa = Convert.ToInt32(empresa);
                objmov.id_categoria = Convert.ToInt32(categoria);
                objmov.id_conta = Convert.ToInt32(conta);

                try
                {
                    objDao.LancarMovimento(objmov);
                    ViewBag.Ret = 1;
                    ViewBag.Msg = Mensagens.Msg.MensagemSucesso;
                }
                catch 
                {
                    ViewBag.Ret = -1;
                    ViewBag.Msg = Mensagens.Msg.MensagemErro;
                    
                }
            }

            CarregarComboCategoria();
            CarregarComboConta();
            CarregarComboEmpresas();
            MontarTitulo(1);

            return View("Lancar");
        }
        public ActionResult Consultar()
        {
            CarregarComboEmpresas();
            CarregarComboCategoria();
            CarregarComboConta();
            MontarTitulo(3);
            return View();
        }



    }
}

Views/Movimento/Consultar.cshtml
@{
    Layout = "~/Views/Shared/_layout.cshtml";
}

@using (Html.BeginForm("Filtrar", "Movimento", FormMethod.Post))
{
    <div class="panel panel-default">

        <div class="form-group">
            <label>Tipo</label>
            <select class="form-control" name="tipo">
                <option value="0">Entrada</option>
                <option value="1">Saída</option>
                <option value="2" selected>Todos</option>
            </select>

        </div>
        <div class="form-group">
            <label>Data inicial</label>
            <input class="form-control" type="date" placeholder="Digite aqui" name="dataIni" value="@ViewBag.dtIni" />
        </div>
        <div class="form-group">
            <label>Data final</label>
            <input class="form-control" type="date" placeholder="Digite aqui" name="dataFim" value="@ViewBag.dtFim" />
        </div>
        <button class="btn btn-warning">Pesquisar</button>
    </div>
}
@if (ViewBag.Mov != null)
{


    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Data</th>
                        <th>Tipo</th>
                        <th>Valor</th>
                        <th>Empresa</th>
                        <th>Categoria</th>
                        <th>Conta</th>
                        <th>Obs</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.Mov)
                    {

                        <tr class="odd gradeX">
                            <td>@item.Data</td>
                            <td>@item.Tipo</td>
                            <td>@item.Valor</td>
                            <td>@item.Empresa</td>
                            <td>@item.Categoria</td>
                            <td>@item.Conta</td>
                            <td>@item.Obs</td>


                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>
}

Views/Movimento/Lancar.cshtml
@{
    Layout = "~/Views/Shared/_layout.cshtml";
}

@using (Html.BeginForm("Gravar", "Movimento", FormMethod.Post))
{

    <div class="form-group">
        <label>Data</label>
        <input class="form-control" type="date" name="data" />
    </div>
    <div class="form-group">
        <label>Tipo</label>
        <select class="form-control" name="tipo">
            <option value="">Selecionte</option>
            <option value="0">Entrada</option>
            <option value="1">Saída</option>
        </select>

    </div>
    <div class="form-group">
        <label>Valor</label>
        <input class="form-control" placeholder="Digite o valor" name="valor" />
    </div>
    <div class="form-group">
        <label>Categoria</label>
        <select class="form-control" name="categoria">
            <option value="">Selecionte</option>
            @foreach (var item in ViewBag.lstCategoria)
            {
                <option value="@item.id_categoria">@item.nome_categoria</option>
            }
        </select>

    </div>
    <div class="form-group">
        <label>Empresa</label>
        <select class="form-control" name="empresa">
            <option value="">Selecionte</option>
            @foreach (var item in ViewBag.lstEmpresa)
            {
                <option value="@item.id_empresa">@item.nome_empresa</option>
            }
        </select>

    </div>
    <div class="form-group">
        <label>Conta</label>
        <select class="form-control" name="conta">
            <option value="">Selecionte</option>
            @foreach (var item in ViewBag.lstConta)
            {
                <option value="@item.id_conta">@item.banco_conta / @item.num_conta / @item.saldo_conta</option>
            }
        </select>

    </div>
    <div class="form-group">
        <label>Observação</label>
        <input class="form-control" placeholder="Digite o nome do site" name="obs" />
    </div>
    <button type="submit" class="btn btn-success">Cadastrar</button>

}