Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAO;

namespace ControleFinanceiroWeb.Controllers
{
    public class EmpresaController : PageBase
    {
        private void MontarTitulo(int tipoPag)
        {
            switch (tipoPag)
            {
                case 1:
                    ViewBag.Titulo = "Cadastro de Empresa";
                    ViewBag.SubTitulo = "Cadastre aqui suas Empresas";
                    break;
                case 2:
                    ViewBag.Titulo = "Alterar Empresa";
                    ViewBag.SubTitulo = "Altere aqui suas Empresas";
                    break;
                case 3:
                    ViewBag.Titulo = "Consulta de Empresa";
                    ViewBag.SubTitulo = "Consulte aqui suas Empresas";
                    break;
            }
        }
        // GET: Empresa
        public ActionResult Cadastrar()
        {
            MontarTitulo(1);
            return View();
        }
        public ActionResult Gravar(string cod, string nome, string telefone, string end, string site, string btn)
        {
            if (CodigoLogado == 0)
            {
                return RedirectToAction("Login", "Usuario");
            }

            string pagina = "";
            if (btn == "excluir")
            {
                int codEmp = Convert.ToInt32(cod);
                EmpresaDAO objDao = new EmpresaDAO();
                try
                {
                    objDao.ExcluirEmpresa(codEmp);
                    ViewBag.Ret = 1;
                    ViewBag.Msg = Mensagens.Msg.MensagemSucesso;
                }
                catch
                {

                    ViewBag.Ret = -1;
                    ViewBag.Msg = Mensagens.Msg.MensagemErroExclusao;
                }
                pagina = "Consultar";
                CarregarEmpresas();
                MontarTitulo(3);
            }
            else
            {
                if (nome.Trim() == "" || telefone.Trim() == "" || end.Trim() == "")
                {
                    ViewBag.Ret = 0;
                    ViewBag.Msg = Mensagens.Msg.MensagemCampoObg;
                    if (cod == null)
                    {
                        pagina = "Cadastrar";
                        MontarTitulo(1);
                    }
                    else
                    {
                        pagina = "Alterar";
                        MontarTitulo(3);
                    }
                }
                else
                {
                    tb_empresa objEmpresa = new tb_empresa();
                    EmpresaDAO objDao = new EmpresaDAO();
                    objEmpresa.nome_empresa = nome;
                    objEmpresa.telefone_empresa = telefone;
                    objEmpresa.end_empresa = end;
                    objEmpresa.site_empresa = site;
                    objEmpresa.id_usuario = CodigoLogado;
                    objEmpresa.datacad_empresa = DateTime.Now;

                    MontarTitulo(2);
                    try
                    {
                        if (cod == null)
                        {
                            objDao.InserirEmpresa(objEmpresa);
                            pagina = "Cadastrar";
                            MontarTitulo(1);
                        }
                        else
                        {
                            objEmpresa.id_empresa = Convert.ToInt32(cod);
                            objDao.AlterarEmpresa(objEmpresa);
                            pagina = "Consultar";
                            MontarTitulo(3);
                            CarregarEmpresas();
                        }
                        ViewBag.Ret = 1;
                        ViewBag.Msg = Mensagens.Msg.MensagemSucesso;
                    }
                    catch (Exception)
                    {
                        if (cod == "")
                        {
                            pagina = "Cadastrar";
                            MontarTitulo(1);
                        }
                        else
                        {
                            pagina = "Alterar";
                            MontarTitulo(3);
                        }
                        ViewBag.Ret = -1;
                        ViewBag.Msg = Mensagens.Msg.MensagemErro;
                    }
                }


            }
            return View(pagina);
        }
        public ActionResult Alterar(int cod, string nome, string end, string tel, string site)
        {
            ViewBag.cod = cod;
            ViewBag.nome = nome;
            ViewBag.tel = tel;
            ViewBag.end = end;
            ViewBag.site = site;
            MontarTitulo(2);
            return View();
        }
        private void CarregarEmpresas()
        {
            EmpresaDAO objDao = new EmpresaDAO();
            List<tb_empresa> lstEmpresa = objDao.ConsultarEmpresa(CodigoLogado);
            ViewBag.LstEmpresa = lstEmpresa;
        }
        public ActionResult Consultar()
        {
            CarregarEmpresas();
            MontarTitulo(3);
            return View();
        }

    }
}

Views/Empresa/Alterar.cshtml
@{
    Layout = "~/Views/Shared/_layout.cshtml";
}
@using (Html.BeginForm("Gravar", "Empresa", FormMethod.Post))
{
  
    <input type="hidden" name="cod" value="@ViewBag.cod" />
    <div class="form-group">
        <label>Nome da Empresa</label>
        <input class="form-control" placeholder="Digite o nome da empresa" name="nome" value="@ViewBag.nome" />
    </div>
    <div class="form-group">
        <label>Endereço da Empresa</label>
        <input class="form-control" placeholder="Digite o endereço da empresa" name="end" value="@ViewBag.end" />
    </div>
    <div class="form-group">
        <label>Telefone da Empresa</label>
        <input class="form-control" placeholder="Digite o nome da empresa" name="telefone" value="@ViewBag.telefone" />
    </div>
    <div class="form-group">
        <label>Site da Empresa</label>
        <input class="form-control" placeholder="Digite o site da empresa" name="site" value="@ViewBag.site" />
    </div>

    <button type="submit" name="btn" value="salvar" class="btn btn-success">Salvar Alteração</button>
    <button type="submit" name="btn" value="excluir" class="btn btn-danger">Excluir</button>
}

Views/Empresa/Cadastrar.cshtml
@{
    Layout = "~/Views/Shared/_layout.cshtml";
}
@using (Html.BeginForm("Gravar", "Empresa", FormMethod.Post))
{

    <div class="form-group">
        <label>Nome da Empresa</label>
        <input class="form-control" placeholder="Digite o nome da Empresa..." name="nome" />
    </div>
    <div class="form-group">
        <label>Telefone</label>
        <input class="form-control" placeholder="( )___________" name="telefone" />
    </div>
    <div class="form-group">
        <label>Endereço</label>
        <input class="form-control" placeholder="Digite o endereço" name="end" />
    </div>
    <div class="form-group">
        <label>Site</label>
        <input class="form-control" placeholder="Digite o nome do site" name="site" />
    </div>
    <button type="submit" class="btn btn-success">Cadastrar</button>
    
}

Views/Empresa/Consultar.cshtml
@{
    Layout = "~/Views/Shared/_layout.cshtml";
}
@using (Html.BeginForm("Gravar", "Empresa", FormMethod.Post))
{
    <input type="hidden" name="cod" value="@ViewBag.cod" />
    <div class="panel panel-default">
        <div class="panel-heading">
            Empresas Cadastradas
        </div>

        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Telefone</th>
                            <th>Endereço</th>
                            <th>Site</th>
                            <th>Ação</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in ViewBag.LstEmpresa)
                        {

                        <tr class="odd gradeX">
                            <td>@item.nome_empresa</td>
                            <td>@item.telefone_empresa</td>
                            <td>@item.end_empresa</td>
                            <td>@item.site_empresa</td>
                            <td><a href="/Empresa/Alterar?cod=@item.id_empresa&nome=@item.nome_empresa&tel=@item.telefone_empresa&end=@item.end_empresa&site=@item.site_empresa" class="btn btn-warning">Alterar</a></td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>


    </div>
}