Controllers/ContaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAO;

namespace ControleFinanceiroWeb.Controllers
{
    public class ContaController : PageBase
    {
        private void MontarTitulo(int tipoPag)
        {
            switch (tipoPag)
            {
                case 1:
                    ViewBag.Titulo = "Cadastro de Conta";
                    ViewBag.SubTitulo = "Cadastre aqui suas Contas";
                    break;
                case 2:
                    ViewBag.Titulo = "Alterar Conta";
                    ViewBag.SubTitulo = "Altere aqui suas Contas";
                    break;
                case 3:
                    ViewBag.Titulo = "Consulta de Conta";
                    ViewBag.SubTitulo = "Consulte aqui suas Contas";
                    break;
            }
        }
        // GET: Conta
        public ActionResult Cadastrar()
        {
            MontarTitulo(1);
            return View();
        }
        public ActionResult Gravar(string nome, string ag, string num_conta, string saldo, string tipo, string cod, string btn)
        {
            if (CodigoLogado == 0)
            {
                return RedirectToAction("Login", "Usuario");
            }

            string pagina = "";
            if (btn == "excluir")
            {
                int codConta = Convert.ToInt32(cod);
                ContaDAO objDao = new ContaDAO();
                CarregarContas();
                try
                {
                    objDao.ExcluirConta(codConta);
                    ViewBag.Ret = 1;
                    ViewBag.Msg = Mensagens.Msg.MensagemSucesso;
                }
                catch (Exception)
                {

                    
                    ViewBag.Ret = -1;
                    ViewBag.Msg = Mensagens.Msg.MensagemErro;
                }
                pagina = "Consultar";
                CarregarContas();
                MontarTitulo(3);
            }
            else
            {
                if (nome.Trim() == "" || ag.Trim() == "")

                {
                    ViewBag.Ret = 0;
                    ViewBag.Msg = Mensagens.Msg.MensagemCampoObg;
                    if (cod == null)
                    {
                        pagina = "Cadastrar";
                        MontarTitulo(1);
                    }
                    else
                    {
                        pagina = "Alterar";
                        MontarTitulo(3);
                    }
                }
                else
                {
                    tb_conta objConta = new tb_conta();
                    ContaDAO objDao = new ContaDAO();

                    objConta.banco_conta = nome.Trim();
                    objConta.ag_conta = ag.Trim();
                    objConta.num_conta = num_conta;
                    objConta.saldo_conta = Convert.ToDecimal(saldo);
                    objConta.tipo_conta = tipo;
                    objConta.data_conta = DateTime.Now;
                    objConta.id_usuario = CodigoLogado;
                    try
                    {
                        if (cod == null)
                        {
                            objDao.InserirConta(objConta);
                            pagina = "Cadastrar";
                            MontarTitulo(1);
                        }
                        else
                        {
                            objConta.id_conta = Convert.ToInt32(cod);
                            objDao.AlterarConta(objConta);
                            pagina = "Consultar";
                            MontarTitulo(3);
                            CarregarContas();
                        }
                        ViewBag.Ret = 1;
                        ViewBag.Msg = Mensagens.Msg.MensagemSucesso;
                    }
                    catch (Exception)
                    {

                        if (cod == "")
                        {
                            pagina = "Cadastrar";
                            MontarTitulo(1);
                        }
                        else
                        {
                            pagina = "Alterar";
                            MontarTitulo(3);
                        }
                        ViewBag.Ret = -1;
                        ViewBag.Msg = Mensagens.Msg.MensagemErro;
                    }
                }
            }

            return View(pagina);

        }
        public ActionResult Alterar(string btn, string cod, string banco, string ag,
            string numero, string saldo, char tipo)
        {
            ViewBag.cod = cod;
            ViewBag.nome = banco;
            ViewBag.ag = ag;
            ViewBag.numero = numero;
            ViewBag.saldo = saldo;
            ViewBag.tipo = tipo;
            MontarTitulo(2);
            return View();
        }
        public ActionResult Consultar()
        {
            CarregarContas();
            MontarTitulo(3);
            return View();
        }

        private void CarregarContas()
        {
            ContaDAO objDao = new ContaDAO();
            List<tb_conta> lstConta = objDao.ConsultarConta(CodigoLogado);
            ViewBag.lstConta = lstConta;
        }
    }
}

Views/Conta/Alterar.cshtml
@{
    Layout = "~/Views/Shared/_layout.cshtml";
}
@using (Html.BeginForm("Gravar", "Conta", FormMethod.Post))
{
    <input type="hidden" name="cod" value="@ViewBag.cod" />
    <div class="form-group">
        <label>Nome do Banco</label>
        <input class="form-control" placeholder="Digite aqui..." name="nome" value="@ViewBag.banco" />
    </div>
    <div class="form-group">
        <label>Número da Agência</label>
        <input class="form-control" placeholder="Digite aqui..." name="ag" value="@ViewBag.ag" />
    </div>
    <div class="form-group">
        <label>Número da Conta</label>
        <input class="form-control" placeholder="Digite aqui..." name="numero" value="@ViewBag.numero" />
    </div>
    <div class="form-group">
        <label>Saldo da Conta</label>
        <input class="form-control" placeholder="Digite aqui..." name="saldo" value="@ViewBag.saldo" />
    </div>
    <label for="TipoConta">Tipo da Conta</label>
    <select id="TipoConta" class="form-control" name="tpconta">
        <option>-Selecione o tipo da conta</option>
        <option value="0" @{ string sel = ""; if (ViewBag.tpconta == "0") { sel = "selected"; } else { sel = ""; } } @sel> Poupança</option>
        <option value="1" @{ if (ViewBag.tpconta == "1") { sel = "selected"; } else { sel = ""; } } @sel> Conta Corrente</option>
    </select>
    <button type="submit" name="btn" value="salvar" class="btn btn-success">Salvar Alteração</button>
    <button type="submit" name="btn" value="excluir" class="btn btn-danger">Excluir</button>
}

Views/Conta/Cadastrar.cshtml
@{
    Layout = "~/Views/Shared/_layout.cshtml";
}
@using (Html.BeginForm("Gravar", "Conta", FormMethod.Post))
{
    <div class="form-group">
        <label>Nome do Banco</label>
        <input class="form-control" placeholder="Digite aqui..." name="nome" />
    </div>
    <div class="form-group">
        <label>Número da agência</label>
        <input class="form-control" placeholder="Digite aqui..." name="ag" />
    </div>
    <div class="form-group">
        <label>Número da Conta</label>
        <input class="form-control" placeholder="Digite aqui..." name="num_conta" />
    </div>

    <div class="form-group">
        <label>Saldo da conta</label>
        <input class="form-control" style="width:500px;" placeholder="Digite aqui..." name="saldo" />
    </div>


    <div class="form-group">
        <label>Tipo</label>
        <select class="form-control" name="tipo">
            <option value="">Selecionte</option>
            <option value="0">Corrente</option>
            <option value="1">Poupança</option>
        </select>

    </div>

    <button type="submit" name="btn" class="btn btn-success">Cadastrar</button>

}

Views/Conta/Consultar.cshtml
@{
    Layout = "~/Views/Shared/_layout.cshtml";
}
@using (Html.BeginForm("Gravar", "Conta", FormMethod.Post))
{
    <input type="hidden" name="cod" value="@ViewBag.cod" />
    <div class="panel panel-default">
        <div class="panel-heading">
            Contas Cadastradas
        </div>

        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead>
                        <tr>
                            <th>Nome do Banco</th>
                            <th>Agência</th>
                            <th>Número</th>
                            <th>Saldo</th>
                            <th>Tipo de Conta</th>
                            <th>Ação</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in ViewBag.lstConta)
                        {

                            <tr class="odd gradeX">
                                <td>@item.ag_conta</td>
                                <td>@item.banco_conta</td>
                                <td>@item.num_conta</td>
                                <td>@item.saldo_conta</td>
                                <td>@item.tipo_conta</td>
                                <td><a href="/Conta/Alterar?cod=@item.id_conta&nome=@item.banco_conta&ag=@item.ag_conta&num_conta=@item.num_conta&saldo=@item.saldo_conta&tipo=@item.tipo_conta" class="btn btn-warning">Alterar</a></td>
                            </tr>

                        }

                    </tbody>
                </table>
            </div>

        </div>

        


    </div>
}